version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis_network
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - redis_network
    restart: unless-stopped

networks:
  redis_network:
    driver: bridge

volumes:
  redis_data:
    driver: local